version: "1"
services:
  db:
    image: mariadb:10
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./backApi/db/conf.d:/etc/mysql/conf.d
      - ./backApi/db/mariadb/conf.d:/etc/mysql/mariadb.conf.d
      - ./backApi/db/data:/var/lib/mysql
      - ./backApi/db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./backApi/db/initdb.d/.env
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - net
  back:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backApi/Dockerfile
    container_name: api
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_HIBERNATE_DDL: create-drop
    networks:
      - net
  front:
    depends_on:
      - back
    ports:
      - 80:80
    build:
      dockerfile: ./front_vue/Dockerfile
    expose:
      - 80
    volumes:
      - "./front_vue/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - net
  socket: # 미완성
    ports:
      - 3000:3000
    build: ./socket_server
    restart: unless-stopped
    networks:
      - net
networks:
  net:
    driver: bridge