version: "1"
services:
  db:
    image: mariadb:10
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/mariadb/conf.d:/etc/mysql/mariadb.conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./db/initdb.d/.env
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']