spring:
  application:
    name: backApi

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop
        #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      generate-ddl: true

jwt:
  key: BackApiServerKey
  header: AuthKey

front-server:
  url: http://localhost:8081