spring:
  application:
    name: backApi
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      #naming:
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: socket
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

front-server:
  local-url: http://localhost:8081
  container-url: http://localhost
  socket-url: http://localhost:3000
  cloud-server: http://ec2-13-125-51-108.ap-northeast-2.compute.amazonaws.com/